name: Parking BeemyFlex
off:
  schedule:
    - cron: '0 12 * * *'   # 12h00 GMT
    - cron: '10 16 * * *'  # 16h10 GMT
    - cron: '0 17 * * *'   # 17h00 GMT
  workflow_dispatch: # Pour tester manuellement

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests
      - name: Lancer la resa
        run: python parking.py
        env:
          BEEMYFLEX_TOKEN: ${{ secrets.BEEMYFLEX_TOKEN }}
